### ISSUE TITLE
project intentions 

### ISSUE THREAD

**Issue by atomGit** [bit-paper/bitboard#1]
given this is a very recent project, and many such projects are quickly abandoned, i'd like to get a sense of the level of commitment if you devs would be so kind

**Comment by nc-gp** [comment]
@atomGit As soon as I stop feeling burned out, I'll definitely continue the project updates

**Comment by sh3rfy** [comment]
@atomGit I'm currently putting all my time into other projects I'm doing privately, but I have no plans to abandon this project, it's just developing at its own pace, I think we should add more features to encourage others outside the team to participate in the development, currently no one wants to because of the gaps in the overall design of this project and what we want to achieve

**Comment by atomGit** [comment]
i appreciate the comments guys and i'll be keeping an eye on development

**Comment by bozyzaf** [comment]
In my example, I don't have time until Christmas to develop the project. Unfortunately, I still have my last year of school and a class to pass. 

This year will be a busy year at school, but we'll see what the 2nd school term will bring - hopefully some more rest.

I immediately add that I do not have in my thoughts to abandon the project, but constantly develop it. :)

**Thank you and best regards,
zanxy.**
